# ### Create User
# POST http://localhost:8080/api/users
# Content-Type: application/json

# {
#   "username": "mongoAdmin",
#   "password": "1234",
#   "role": "ADMIN"
# }
# POST http://localhost:8080/api/students/6991cea0133ac4fe99f80e5b
# Content-Type: application/json

# {
#   "name": "Rahul Sharma",
#   "rollNo": "23",
#   "className": "10-A",
#   "phone": "9876543210"
# }

# POST http://localhost:8080/api/auth/login
# Content-Type: application/json

# {
#   "username": "mongoAdmin",
#   "password": "1234"
# }


# GET http://localhost:8080/api/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb25nb0FkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzcxMTY2ODgxLCJleHAiOjE3NzEyNTMyODF9.oVRzyILhRAfXrVJBpNIKJAU-3L7QUS3I8_JniPwkC7o
# POST http://localhost:8080/api/students/6991cea0133ac4fe99f80e5b
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb25nb0FkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzcxMTY2ODgxLCJleHAiOjE3NzEyNTMyODF9.oVRzyILhRAfXrVJBpNIKJAU-3L7QUS3I8_JniPwkC7o

# {
#   "name": "Amit Kumar",
#   "rollNo": "45",
#   "className": "9-B",
#   "phone": "9998887776"
# }

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "admin1",
  "password": "1234",
  "role": "ADMIN"
}





